#!/bin/bash
set -eux
pytest_flags=(
	# --fulltrace
	--noconftest
	--showlocals
	--strict
	--tb=short
	--verbose
	# -n auto
	-ra
)
cd "$( dirname "${BASH_SOURCE[0]}" )/.."
if [[ ! -d ./venv-27 ]] ; then
	virtualenv --python=python2.7 ./venv-27
	./venv-27/bin/pip install -e . pytest{,-randomly,-flake8,-xdist} six mock
fi
if [[ ! -d ./venv-36 ]] ; then
	virtualenv --python=python3.6 ./venv-36
	./venv-36/bin/pip install -e . pytest{,-randomly,-flake8,-xdist} six mock
fi
./venv-27/bin/pytest ${pytest_flags[@]} $@ tests/
./venv-36/bin/pytest ${pytest_flags[@]} $@ tests/
